# Generated by Django 4.2 on 2024-12-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_button', models.CharField(max_length=100)),
                ('slider_image', models.ImageField(upload_to='slides/')),
            ],
        ),
    ]
