# Generated by Django 4.2 on 2025-01-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_button', models.CharField(max_length=100)),
                ('mobile_image', models.ImageField(upload_to='mobiles/')),
                ('mobile_type', models.CharField(max_length=100)),
                ('mobile_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
    ]
