# Generated by Django 4.2 on 2025-01-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_yearly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearly',
            old_name='yearly_title',
            new_name='yearly_discount',
        ),
        migrations.RenameField(
            model_name='yearly',
            old_name='yearly_header',
            new_name='yearly_heading',
        ),
    ]
