# Generated by Django 4.2 on 2025-01-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_rename_yearly_title_yearly_yearly_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_image', models.ImageField(upload_to='latests/')),
                ('latest_date', models.DateField(auto_now=True)),
                ('latest_item', models.CharField(max_length=100)),
                ('latest_description', models.TextField(max_length=500)),
            ],
        ),
    ]
