# Generated by Django 4.2 on 2025-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_description', models.TextField(max_length=500)),
                ('testimonial_author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='latest',
            name='latest_date',
            field=models.DateField(),
        ),
    ]
