# Generated by Django 4.2 on 2025-01-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_testimonial_alter_latest_latest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_title', models.CharField(max_length=100)),
                ('subscription_description', models.TextField(max_length=500)),
                ('subscription_button', models.CharField(max_length=100)),
            ],
        ),
    ]
